// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TML.Storage.Data;

#nullable disable

namespace TML.Storage.Migrations
{
    [DbContext(typeof(TMLDbContext))]
    partial class TMLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TML.Core.Domain.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InheritanceDepth")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Models_CreatedAt");

                    b.HasIndex("InheritanceDepth")
                        .HasDatabaseName("IX_Models_InheritanceDepth");

                    b.HasIndex("ParentModelId")
                        .HasDatabaseName("IX_Models_ParentModelId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Models_Status");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_Models_TransactionId");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("TML.Core.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ProcessingTimeMs")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Transactions_CreatedAt");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_Transactions_Source");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Transactions_Status");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("TML.Core.Domain.Model", b =>
                {
                    b.HasOne("TML.Core.Domain.Model", null)
                        .WithMany()
                        .HasForeignKey("ParentModelId");

                    b.HasOne("TML.Core.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TML.Core.Domain.SpatialLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GridId")
                                .HasColumnType("text");

                            b1.Property<double>("X")
                                .HasColumnType("double precision");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Z")
                                .HasColumnType("double precision");

                            b1.HasKey("ModelId");

                            b1.ToTable("Models");

                            b1.ToJson("Location");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.OwnsOne("TML.Core.Domain.ModelMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision");

                            b1.Property<double>("MeanAbsoluteError")
                                .HasColumnType("double precision");

                            b1.Property<double>("MeanSquaredError")
                                .HasColumnType("double precision");

                            b1.Property<double>("RSquared")
                                .HasColumnType("double precision");

                            b1.Property<double>("RootMeanSquaredError")
                                .HasColumnType("double precision");

                            b1.Property<int>("TrainingDataPoints")
                                .HasColumnType("integer");

                            b1.HasKey("ModelId");

                            b1.ToTable("Models");

                            b1.ToJson("Metrics");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.OwnsOne("TML.Core.Domain.ModelParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Hyperparameters")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Weights")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ModelId");

                            b1.ToTable("Models");

                            b1.ToJson("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.OwnsOne("TML.Core.Domain.PhysicsValidation", "PhysicsValidation", b1 =>
                        {
                            b1.Property<Guid>("ModelId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("EnergyConservationValid")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsValid")
                                .HasColumnType("boolean");

                            b1.Property<bool>("MassConservationValid")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ThicknessValid")
                                .HasColumnType("boolean");

                            b1.Property<double>("ValidationScore")
                                .HasColumnType("double precision");

                            b1.Property<string>("Violations")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ModelId");

                            b1.ToTable("Models");

                            b1.ToJson("PhysicsValidation");

                            b1.WithOwner()
                                .HasForeignKey("ModelId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Metrics")
                        .IsRequired();

                    b.Navigation("Parameters")
                        .IsRequired();

                    b.Navigation("PhysicsValidation")
                        .IsRequired();
                });

            modelBuilder.Entity("TML.Core.Domain.Transaction", b =>
                {
                    b.OwnsOne("TML.Core.Domain.TransactionData", "Data", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Features")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("MinThickness")
                                .HasColumnType("double precision");

                            b1.Property<double>("Quality")
                                .HasColumnType("double precision");

                            b1.Property<double>("Thickness")
                                .HasColumnType("double precision");

                            b1.Property<double>("XCoord")
                                .HasColumnType("double precision");

                            b1.Property<double>("YCoord")
                                .HasColumnType("double precision");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.ToJson("Data");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("System.Collections.Generic.Dictionary<System.String,System.Object>", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Data")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
